// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "0dd7a36b-d1eb-489f-9fde-8bc026bbfa38");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1621668584);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1621668659);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1621669584);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1621668614);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.engagement.downloads-button.has-used", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1621668553);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d1d7f2d0-2722-4485-839d-6bc06a805793}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1621668558);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1621668603609");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1621670430609");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1621668565156");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1621690165156");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210506154205");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1621669584");
user_pref("browser.startup.homepage_override.buildID", "20210506154205");
user_pref("browser.startup.homepage_override.mstone", "88.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1621669584);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1621668560552");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "88.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "c8402efdfb1c478e8447b5c14d8ee0dd");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210506154205");
user_pref("extensions.lastAppVersion", "88.0.1");
user_pref("extensions.lastPlatformVersion", "88.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"4befad37-a539-495a-85db-e62ae5d4d753\",\"formautofill@mozilla.org\":\"7234adf4-c892-4dcb-88a1-f1d8e8b8733c\",\"pictureinpicture@mozilla.org\":\"ec9ad363-56a7-4714-a2e1-c5d2e3fbc459\",\"screenshots@mozilla.org\":\"af6d7189-185f-4657-8652-f262176ea9ba\",\"webcompat-reporter@mozilla.org\":\"9d8fcee7-e5af-43cd-999c-00f024b09ac1\",\"webcompat@mozilla.org\":\"1db12f4d-4046-4d62-a4b1-3e9a23fda52e\",\"default-theme@mozilla.org\":\"cc234900-b6dc-49b0-a8e7-cfd890fb56b7\",\"google@search.mozilla.org\":\"f2207ff1-08ab-42a0-aa39-f2c9ce31c649\",\"amazondotcom@search.mozilla.org\":\"782813aa-ed41-461d-b8d1-db79b05321c5\",\"wikipedia@search.mozilla.org\":\"fcc3fa0f-5b58-4fe1-b0bc-cf05622ee1a0\",\"bing@search.mozilla.org\":\"3ecbcf12-964d-43af-bf33-670c60658bf6\",\"ddg@search.mozilla.org\":\"5474e63c-9418-4336-bbaf-f0b605682edf\",\"firefox-compact-dark@mozilla.org\":\"bf3c061f-8fea-4e2d-ade9-760fcf134e1f\",\"addon@darkreader.org\":\"6ff99da7-ed24-4911-9753-9644468a6e5d\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1621668560);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "0bc86c23-a64a-4f3b-b423-630d66fc361f");
user_pref("security.sandbox.plugin.tempDirSuffix", "6292dcea-7971-40c4-8048-a59798e8237e");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1621669583);
user_pref("toolkit.telemetry.cachedClientID", "bc4d7b74-0ec7-47a8-8d74-b705304857a3");
user_pref("toolkit.telemetry.previousBuildID", "20210506154205");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
